/* Problem set 1 - Problem 1
-- OBJECTIVE --

Name: Jose Ramos
Date: September 20, 2019

Write a program that  defines an array of 100 doubles. Use loops to complete the following:

    - Fill the array with random values generated by the Random class
    - Print the array
    - Find the greatest value in the array
    - Find the lowest value in the array
    - Find the average of all the values
*/

import java.util.*;
import java.lang.*;

public class FirstProblem {

    public static void main(String[] args) {

        // Declaring a Random type variable to generate a random int number
        Random rand = new Random();

        int[] array_of_100_number = new int[100];

        // Giving a random value to each index in the array
        for (int i = 0; i<100; i++){
            array_of_100_number[i] = rand.nextInt(1000);
        }

        // Printing all the values in the array
        System.out.print("[ ");
        for (int number: array_of_100_number) {
            System.out.print(number + " ");
        }
        System.out.println("]");

        int lowest_value = array_of_100_number[0];
        int greatest_value = 0;
        int average_value = 0;

        // The next loop is printing all the values in the array.
        for (int i = 0; i < array_of_100_number.length; i++){
            if(array_of_100_number[i] > greatest_value){
                greatest_value = array_of_100_number[i];
            }
            if(array_of_100_number[i] < lowest_value){
                lowest_value = array_of_100_number[i];
            }
            average_value += array_of_100_number[i];

            if (i == array_of_100_number.length - 1){
                average_value /= array_of_100_number.length;
            }
        }

        // The next print statements are printing the the greatest, lowest and average number in the array.
        System.out.println("The greatest value in the array is: " + greatest_value);
        System.out.println("The lowest value in the array is: " + lowest_value);
        System.out.println("The average value in the array is: " + average_value);
    }
}
